/**
 * TsuryPhone Types
 * Type definitions for TsuryPhone device state and API
 */

export interface TsuryPhoneState {
  // Quick Dials (Contacts)
  quick_dials: QuickDialEntry[];

  // Blocked Numbers
  blocked_numbers: BlockedNumberEntry[];

  // Priority Numbers (array of numbers)
  priority_numbers: string[];

  // Call History
  call_history: CallHistoryEntry[];

  // Current call state
  app_state: AppState;
  current_call: CallInfo;
  waiting_call: CallInfo;

  // Dialing
  dialing_context: {
    default_code: string;
    send_mode_enabled: boolean;
  };

  // Volume
  volume_mode: "EARPIECE" | "SPEAKER";

  // Mute state
  is_muted: boolean;
}

export interface QuickDialEntry {
  id: string; // Unique identifier (auto-generated by backend)
  code: string; // Optional quick dial code (can be empty)
  number: string; // Normalized E.164 format
  name: string;
  display_number: string;
}

export interface BlockedNumberEntry {
  id: string;
  number: string; // Normalized E.164 format
  name: string;
  display_number: string;
}

export interface CallHistoryEntry {
  call_type: string; // "incoming" | "outgoing" | "blocked" | "missed"
  number: string;
  name: string;
  normalized_number: string;
  is_incoming: boolean;
  duration_s: number | null;
  duration_ms: number | null;
  ts_device: number;
  received_ts: number;
  call_start_ts: number;
  reason: string | null;
  is_priority: boolean;
}

export interface CallInfo {
  number: string;
  name?: string;
  is_incoming: boolean;
  is_priority: boolean;
}

export enum AppState {
  IDLE = "IDLE",
  DIALING = "DIALING",
  CALLING_OUT = "CALLING_OUT",
  RINGING_IN = "RINGING_IN",
  IN_CALL = "IN_CALL",
  INVALID_NUMBER = "INVALID_NUMBER",
}

export interface TsuryPhoneCardConfig {
  type: "custom:tsuryphone-card";
  entity?: string; // Optional: full entity ID (e.g., sensor.phone_state)
  device_id?: string; // Optional: defaults to 'tsuryphone'
  show_frequent_contacts?: boolean; // Optional: defaults to true
  frequent_contacts_refresh_hours?: number; // Optional: defaults to 24
}
